#!/usr/bin/env php
<?php

declare (strict_types=1);

use Symfony\Component\Console\Output\ConsoleOutput;
use Tcds\Io\Player\Exception\PlayerException;
use Tcds\Io\Player\Formatter;
use Tcds\Io\Player\Player;

include __DIR__ . '/../../autoload.php' ?? throw new Exception('Missing ');
$playerFile = __DIR__ . '/../../../player.php';

/**
 * creates config
 */
if (!is_file($playerFile)) {
    copy(__DIR__ . '/player.php.sample', $playerFile);
}

$config = include __DIR__ . '/../../../player.php';
$console = new ConsoleOutput();

try {
    Player::create()->check($config);
    $console->writeln('');
    $console->writeln(Formatter::success('No leaking imports'));
} catch (PlayerException $exception) {
    $console->writeln($exception->output());

    exit(1);
}
